#Play Intall httpd
- name: Install httpd
  hosts: webservers_centos
  become: True
  tasks:
  - name: Install httpd
    yum:
      name: "httpd"
      state: "present"  

  - name: Start Apache Server
    ansible.builtin.service:
      name: httpd
      state: started
      enable: yes

  - name: Deploy static website
    copy:
      src: index.html
      dest: /var/www/html

  - name: allow http service
    command:
      cmd: firewall-cmd --permanent --add-service=http
      
  - name: reload firewalld
    command:
      cmd: firewall-cmd --reload

  - name: check status
    command:
      cmd: systemctl status httpd
    register: result
      
  - name: show result on screen 
    debug: var=result.stdout_lines

...